"""adiciona coluna created_at em feedbacks

Revision ID: 0ff9c9b33b6b
Revises: 2078179a6840
Create Date: 2026-01-08 18:08:09.381393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff9c9b33b6b'
down_revision: Union[str, None] = '2078179a6840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'created_at')
    # ### end Alembic commands ###
